src/main/java/org/duckdb/DuckDBDatabaseMetaData.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/test/Assertions.java
This PR allows `DECIMAL(W,S)` types to be interpreted as `DECIMAL` JDBC type. Currently the type is returned as a generic `JAVA_OBJECT` because  `DECIMAL(W,S)` does not match ` `DECIMAL` in the case statement. This is similar to [0.9.2 behavior](https://github.com/duckdb/duckdb/blob/v0.9.2/tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java#L832) except the start-of-string matching is done in SQL rather than [Java](https://github.com/duckdb/duckdb/blob/v0.9.2/tools/jdbc/src/main/java/org/duckdb/DuckDBResultSetMetaData.java#L49).
I wonder if a better fix would be to use `data_type_id` from `duckdb_columns()` rather than `data_type` from `information_schema.columns`? It would require adding hardcoded duckdb type numbers into `DuckDBColumnType`. The test is useful either way. …
=> Fix JDBC type for DECIMAL columns; add test

src/main/java/org/duckdb/DuckDBResultSet.java, src/main/java/org/duckdb/DuckDBVector.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/test/Assertions.java
Fixes duckdb/duckdb-java#24.  
Adds support for the getBytes() method in DuckDBResultSet, along with accompanying unit test.
=> Add get bytes

CODE_OF_CONDUCT.md, LICENSE
Current duckdb-java repo doesn't have a LICENSE file or code of conduct, after being split out of the main repo.  This could be problematic.  Adding versions from main repo.
=> Add LICENSE and code of conduct files from main DuckDB project.

.github/workflows/Java.yml
Uploading this artifact currently relies on the upload to Maven succeeding because it's uploaded within the same step. However, we'd like to have the combined JAR available even if it does not succeed (which is very often). This PR separates this step and allows it to always run even if the previous step failed.
=> Always upload combined JAR even if Maven upload fails

.github/workflows/Java.yml, .github/workflows/Nightly.yml
Trigger rebuild (= then deployed on latest) also for nightly vendoring script.
I have tested this on my fork, looks to be working as intended, but possibly some permissions might be off, unsure, we will need to check whether it works in the proper context to double check.
Pinging @lnkuiper, that pinged on this.
=> Trigger rebuild also on Nightly

src/main/java/org/duckdb/DuckDBDatabaseMetaData.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
JDBC describes that COLUMN_SIZE for a DECIMAL type should reflect its total number of digits, whereas DECIMAL_DIGITS describes it numeric scale.
See: https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)
This does the right thing for all other types (where numeric_precision is null), *except* for INTEGER and LONG, where currently in DuckDB this reports 32 and 64, resp, where it should report 10 and 19. That's for another PR, I think.
=> Fix metadata reflection for DECIMAL columns - with test

src/main/java/org/duckdb/DuckDBDatabaseMetaData.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This allows using \ to escape the LIKE expressions in schema reflection.
=> Allow escaping in schema reflection - with test

src/main/java/org/duckdb/DuckDBPreparedStatement.java
I realize that one use the Appender instead, but I did notice that we force a transaction per row even when auto-commit is off.
This uses a transaction per batch instead. Looks like this is already covered in the tests, please let me know if you think that's not sufficient.
Roughly a 2x improvement in tests (this is a using DuckDB from Trino).
=> Use a single transaction per batch

src/jni/duckdb_java.cpp, src/main/java/org/duckdb/DuckDBVector.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
=> fix: blob usage after resultset move

.github/workflows/Java.yml
This action needs to be updated to allow workflow runs, [details](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
=> Update upload-artifact action to v4

.github/workflows/Java.yml, CMakeLists.txt, CMakeLists.txt.in
The jemalloc extention was recently added to JDBC builds in #133. The logic for its selection in `vendor.py` does not look fully correct to me, but both Linux and Mac are passing on CI, only Windows is breaking, so this change only tries to unbreak Windows builds, and the jemalloc selection logic can be improved in subsequent PRs.
=> Do not build jemalloc on Windows

src/jni/duckdb_java.cpp, src/main/java/org/duckdb/DuckDBVector.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
When parsing an UUID from a string literal DuckDB modifies it with [flipping the most significant bit](https://github.com/duckdb/duckdb/blob/c9dd40f144e07a5dddb1d81c7218555205894c80/src/common/types/uuid.cpp#L51) in `UUID::FromString` for the following reason:
"Flip the first bit to make `order by uuid` same as `order by uuid::varchar`"
When an UUID is read from a result set, JDBC driver flips the MSB again to get back the original UUID in Java.
This bit-flipping logic was missing when an UUID was passed from Java as a bind variable. The proposed change adds the same logic when passing bind variables.
Testing: existing test is improved to cover both string literal and a bind variable.
Fixes: #147
=> Modify UUID when passing it as a bind variable

.github/workflows/Nightly.yml
This PR brings the duckdb/duckdb-odbc#87 change to JDBC repo.
Testing: no code changes, no new tests.
=> Support engine commit ID parameter to vendor CI

CMakeLists.txt, CMakeLists.txt.in, vendor.py
This change is a follow-up to #162, it moves platform-specific jemalloc selection logic from `vendor.py` to CMake. Additionally CMake file is restructured and cleaned up.
Testing: no functional changes, no new tests.
=> Move jemalloc selection logic to CMake

src/main/java/org/duckdb/DuckDBDatabaseMetaData.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
A few schema introspection functions in `DatabaseMetadata` take `catalog` and `schemaPattern` parameters with the following specific requirements:
> catalog - a catalog name; must match the catalog name as it is stored in the database; "" retrieves those without a catalog; null means that the catalog name should not be used to narrow the search
> schemaPattern - a schema name pattern; must match the schema name as it is stored in the database; "" retrieves those without a schema; null means that the schema name should not be used to narrow the search
This change makes the handling for these parameters consistent between `getSchemas`, `getTables`, `getColumns`, `getPrimaryKeys`, `getIndexInfo` and `getFunctions` functions. Additionally it fixes the escaping for `functionNamePattern` …
=> DatabaseMetadata schema introspection enhancements

src/main/java/org/duckdb/DuckDBResultSet.java, src/main/java/org/duckdb/DuckDBTimestamp.java, src/main/java/org/duckdb/DuckDBVector.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
DuckDB supports both `TIMESTAMP WITHOUT TIME ZONE` and `TIMESTAMP WITH TIME ZONE`. When gettting Java `Timestamp` from a result set, user can optionally request desired time zone by specifying a `Calendar` instance.
Thus we are getting the following invariants:
1. `TIMESTAMP WITH TIME ZONE`, no `Calendar`: returns `Timestamp` in a system-default (JVM) time zone that represents the same moment in time as the DB's `TIMESTAMP WITH TIME ZONE`. For example with a system-default time zone being `EET` (`UTC+2`) the timestamp with `12:00` time and `CET` (`UTC+1`) DB time zone will be returned with `13:00` time (in `EET`).
2. `TIMESTAMP WITH TIME ZONE`, user-specified Calendar: the same logic is used as in point `1.`, just the time-zone from the user-specified Calendar is used instead of the …
=> Result set Timestamp handling improvements

CMakeLists.txt, src/jni/duckdb_java.cpp, src/jni/types.cpp, src/jni/types.hpp, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/TestExtensionTypes.java, src/test/java/org/duckdb/TestSpatial.java, src/test/java/org/duckdb/test/Assertions.java, src/test/java/org/duckdb/test/Runner.java
This PR changes the handling of extension types. Instead of treating
all custom types (detected by having an alias) as `VARCHAR`, it ignores
type alias and uses underlying logical type.
This allows to work with the following types from the spatial
extension using default JDBC types `java.sql.Struct`, `java.sql.Array`,
and `java.sql.Blob`:
- `POINT_2D`: as `STRUCT{x: DOUBLE, y: DOUBLE}`
- `POINT_3D`: as `STRUCT{x: DOUBLE, y: DOUBLE, z: DOUBLE}`
- `POINT_4D`: as `STRUCT{x: DOUBLE, y: DOUBLE, z: DOUBLE, m: DOUBLE}`
- `LINESTRING_2D`: as `LIST[STRUCT{x: DOUBLE, y: DOUBLE}]`
- `POLYGON_2D`: as `LIST[LIST[STRUCT{x: DOUBLE, y: DOUBLE}]]`
- `BOX_2D`: as `STRUCT{min_x: DOUBLE, max_x: DOUBLE, min_y: DOUBLE, max_y: DOUBLE}`
- `BOX_2DF`: as `STRUCT{min_x: FLOAT, max_x: FLOAT, min_y: FLOAT, max_y: …
=> Support spatial extension types

src/jni/duckdb_java.cpp, src/test/java/org/duckdb/TestDuckDBJDBC.java
This change copies `ClientConfig` to a new connection on `duplicate()` call.
Testing: new test added that checks that `home_directory` value is retained in a duplicated connection.
Fixes: #148
=> Retain client config on connection duplication

.github/workflows/Java.yml
JDBC compliance test runs use the scripts from
https://github.com/cwida/jdbccts repo. CMake script in this repo became broken after the CMake 4.0 update on CI runners. It now breaks with the following message:
```
Compatibility with CMake < 3.5 has been removed from CMake.
```
There is an [ongoing activity](https://github.com/cwida/jdbccts/pull/1) to fix this in `jdbcct`, meanwhile this change temporary disables compliance CI runs until the fix is applied.
=> Temporary disable compliance CI runs

.github/workflows/Java.yml
This reverts commit 9cbfad4be339663821671398ff6c23f8bcda5f05.
The https://github.com/cwida/jdbccts/pull/1 PR was just merged so compliance test should work again now.
=> Re-enable compliance test runs on CI

src/jni/duckdb_java.cpp, src/jni/refs.cpp, src/main/java/org/duckdb/DuckDBParameterMetaData.java, src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/main/java/org/duckdb/DuckDBResultSetMetaData.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/TestParameterMetadata.java
This PR brings in the change that was contributed earlier by `eramitmittal` in #114 but was not merged. That change is rebased onto the latest `main`with minimal adjustetments.
Testing: in addition to the `DECIMAL` test from original PR more tests are added to cover all other column types.
Fixes: #121
Fixes: #41
=> Implement ParameterMetadata

src/main/java/org/duckdb/DuckDBConnection.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
[Connection#getTypeMap()](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#getTypeMap--) and [setTypeMap()](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#setTypeMap-java.util.Map-) are two legacy methods that were added to Java in 1998 to support mapping composite DB fields to custom Java classes. With widespread use or object-relational mapping libraries (like Hibernate) these method remain virtually unused in Java applications. Still these method may be called by some tools, for example, when doing DB schema introspection.
Looking how these methods work in other JDBC drivers, we can see that in Postgres' `pgjdbc` the type map is accepted, but [not used for actual field mapping](https://github.com/pgjdbc/pgjdbc/blob/156d724e1d95052b41a19fb568b2f81919 …
=> Allow to use empty typeMap on Connection

src/main/java/org/duckdb/DuckDBArrayResultSet.java, src/main/java/org/duckdb/DuckDBResultSet.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This change brings in the #43 PR with additional changes to the `Array` result set requested by the reviewer in #43.
For the `Array` result set the column names `INDEX` and `VALUE` are taken from the [implementation in Postgres' pgjdbc driver](https://github.com/pgjdbc/pgjdbc/blob/156d724e1d95052b41a19fb568b2f81919ae2197/pgjdbc/src/main/java/org/postgresql/jdbc/PgArray.java#L399).
Testing: test from #43 is included, test for `Array` result set is enhanced with additional checks.
Fixes: #40
=> Make ResultSet getters case insensitive

.github/workflows/Java.yml
This change attemts to use `ubuntu-latest` instead of `ubuntu-20.04` for JDBC compliance test suite run on GH actions.
Fixes: #191
=> Update Ubuntu image used for compiance runs

src/main/java/org/duckdb/DuckDBDriver.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
Apache Spark passes the `path` option when a SELECT on a JDBC DataSource table is performed. It is the internal Spark option and is likely passed by mistake, so we need to ignore it to allow the connection to be established.
Testing: new test added that checks that the `path` option is ignored.
Fixes: #55
=> Ignore path option passed by Spark

scripts/jdbc_maven_deploy.py
DuckDB is using 3-part version number. Sometimes it may be necessary to make an updated JDBC release with the changes only in JDBC/JNI code keeping the engine version the same. For this it is proposed to add fourth component to version number for JDBC-specific changes. So the version is supposed to look like `v1.2.2.0`.
Testing: JAR bundling with 4-part version was tested in a separate repo.
=> Enable 4-part version number

.github/workflows/Vendor.yml
This PR brings duckdb/duckdb-odbc#84 changes to JDBC repo.
Testing: no code changes, no new tests.
=> Use engine commit hash when vendoring sources

CMakeLists.txt, CMakeLists.txt.in, src/jni/duckdb_java.cpp, src/jni/functions.cpp, src/jni/holders.hpp, src/main/java/org/duckdb/DuckDBAppender.java, src/main/java/org/duckdb/DuckDBConnection.java, src/main/java/org/duckdb/DuckDBDatabaseMetaData.java, src/main/java/org/duckdb/DuckDBNative.java, src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/main/java/org/duckdb/DuckDBResultSet.java, src/test/java/org/duckdb/TestClosure.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/test/Assertions.java
This is a version 3 of this PR that attempts to safely close pending
statements when the connection is closed. In it all tracking and
locking logic is moved from C++ to Java:
- `Connection`, `Statement` and `ResultSet` instances use their own
locks; the check that corresponding reference is still alive is
performed before every native call after obtaining the lock.
- `Statement` lock is held during the query execution, note, this lock
is NOT requied to call `statement#cancel()` because this operation is
implemented on a `Connection` level.
- When a `Connection` is being closed, pending query is cancelled
first, and then all active statements are closed in a reverse creation
order.
Note, thread safety for Appender and Arrow interfaces is going to be
addressed in subsequent PRs.
Testing: …
=> Close pending statements on connection close

src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/main/java/org/duckdb/DuckDBTime.java, src/main/java/org/duckdb/DuckDBTimestamp.java, src/main/java/org/duckdb/JdbcUtils.java, src/main/java/org/duckdb/io/IOUtils.java, src/main/java/org/duckdb/io/LimitedInputStream.java, src/main/java/org/duckdb/io/LimitedReader.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/TestTimestamp.java
This change implements a number of setter methods on `PreparedStatement` that were previously throwing
`SQLFeatureNotSupportedException`.
`set*Stream` group of methods is implemented only for compatibility with existing tools, no actual streaming is used on DB level - full input is read to string/bytes before passing it to DB.
`execute`/`executeUpdate` methods for generated keys are implemented only for cases when generated keys are not requested.
`setTime/Date/Timestamp` methods with `Calendar` (time zone) support are implemented fully following the same approach used before in #166. Also the logic for `setTime` method without `Calendar` is fixed to correctly NOT use default JVM time zone.
Testing: new tests added to cover implemented methods; timestamp tests are moved to separate file …
=> Prepared statement enhancements

src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/TestPrepare.java
This change implements a group of `Large` methods, like `executeLargeUpdate`, that were added in Java 8 (JDBC 4.2).
Testing: existing prepared statement tests are moved to a separate file and updated to cover all `Large` methods.
Fixes: #205
=> More prepared statement enhancements

src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestBatch.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/TestNumeric.java
Currently the error message reported by `executeBatch` method is incorrect because this method tries to clear the batch on exit and such clearance is not possible when the statement is already closed after the error. This change adds a check that the statement is open before doing the cleanup.
Testing: existing test is enhanced to check this error message; batch tests are moved to separate file.
=> Minor fix to executeBatch

src/main/java/org/duckdb/DuckDBConnection.java, src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestBatch.java
This change makes `executeBatch()` method to be run in a single transaction when auto-commit is enabled. When auto-commit is disabled, the logic remains the same as before.
Testing: new tests added to check auto-commit and rollback behaviour of `executeBatch()`.
=> Run executeBatch in a single transaction

.github/workflows/Java.yml, .github/workflows/Vendor.yml
This change adds debugging job for vendoring process to investigate why vendoring PRs are not closed automatically (job skipped), while the check expression for it looks correct.
It also adds a number of minor cleanups to workflows.
=> Minor improvements to GH workflows

src/duckdb/extension/json/json_functions/json_table_in_out.cpp, src/duckdb/src/function/table/version/pragma_version.cpp, src/duckdb/src/include/duckdb/main/connection.hpp, src/duckdb/src/main/connection.cpp, src/duckdb/src/optimizer/statistics/operator/propagate_filter.cpp, src/duckdb/src/optimizer/statistics/operator/propagate_get.cpp
Changes:
- [duckdb/duckdb#027bc16ee8](https://github.com/duckdb/duckdb/commit/027bc16ee8) imported at 2025-05-11 06:47:24
=> Update vendored DuckDB sources to 027bc16ee8

.github/workflows/Vendor.yml
This change improves the check in the DuckDB engine sources vendoring process. If no changes are detected in the incoming sources then the remaining of the `Vendor.yml` job is skipped instead of moving it to "Failure" state.
Testing: debugged this in a separate repo.
=> Do not fail Vendor.yml when no changes imported

src/test/java/org/duckdb/TestDuckDBJDBC.java
This change enables Spatial extension tests on GitHub CI runs. With recent improvements in DuckDB engine vendoring process it is expected that JDBC builds can only be done with engine version for that the full set of prebuilt extensions is available, thus `INSTALL spatial` must work.
=> Enable extension tests on CI

src/duckdb/src/function/table/arrow_conversion.cpp, src/duckdb/src/function/table/version/pragma_version.cpp
Changes:
- [duckdb/duckdb#71c5c07cdd](https://github.com/duckdb/duckdb/commit/71c5c07cdd) imported at 2025-05-21 16:59:15
=> Update vendored DuckDB sources to 71c5c07cdd

src/main/java/org/duckdb/DuckDBDriver.java
There is a usability gap with using DuckLake with JDBC, when a connection must be opened first and then the following statement must be executed:
```
ATTACH 'ducklake:...'
```
Executing this additional `ATTACH` step, when accessing DuckLake from GUI tools or from high-level engines like Spark, is cumbersome and may require non-trivial configuration.
This change adds two new connection properties:
1. `ducklake`: the `database-path` parameter to pass to `ATTACH '<database-path>'`.
Value examples:
```
/path/to/lake1.db
sqlite:/path/to/lake1.db
postgres:postgresql://user:pwd@127.0.0.1:5432/lake1
```
If `ducklake:` prefix to the value of this option is not specified - it is added automatically.
Before running the `ATTACH` it also runs:
```
INSTALL ducklake
LOAD ducklake
```
2. …
=> Support auto-initializing DuckLake

src/main/java/org/duckdb/DuckDBConnection.java, src/main/java/org/duckdb/DuckDBDriver.java, src/main/java/org/duckdb/JdbcUtils.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
JDBC spec requires the driver to have `autoCommit` enabled on newly created connections. Changing `autoCommit` using `conn#setAutoCommit()` may be not convenient in some environments with limited access to Java API (e.g. Spark SQL).
This change adds a new `jdbc_auto_commit` connection property that allows to create connections with `autoCommit` disabled.
Testing: new test added to check that property is effective and that the default mode is unchanged.
=> Support disabling auto-commit mode in properties

src/main/java/org/duckdb/DuckDBDriver.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This change adds support for specifying connection properties as part of the connection string itself. It is intended to be used in cases, when `Properties` map is passed by some tool that does not allow direct access to it, and some of these `Properties` values need to be overridden.
Properties in URL are accepted in `key=value` format, `;` is used as a separator, empty properties are ignored.
URL example: `jdbc:duckdb:;allow_community_extensions=true;;allow_unsigned_extensions = false;`.
Testing: new test added that checks that properties in URL take preference.
=> Support connection properties in URL

src/main/java/org/duckdb/DuckDBDriver.java, src/main/java/org/duckdb/JdbcUtils.java
This PR adds the following changes to DuckLake init:
- if `ducklake_alias` option is not specified, then default value `ducklake` is used for it
- when default URL `jdbc:duckdb:` or explicit memory URL `jdbc:duckdb:memory:` is used, then this URL is changed to `jdbc:duckdb:memory:ducklakemem` to be able to share this DB across multiple connections
- DB pinning is enabled automatically (unless disabled by user)
- Result set streaming is enabeld automatically (unless disabled by user)
- DuckLake initialization is done only once for each DB (and each DuckLake path), `ATTACH IF NOT EXISTS` call is changed to `ATTACH`
Testing: test coverage pending, DuckLake is not yet available in `main` branch.
=> Use default alias and DB pinning for DuckLake

src/main/java/org/duckdb/DuckDBResultSet.java, src/test/java/org/duckdb/TestResults.java
Result set method `getObject(idx, class)` requires the driver to convert the requested value to the specified class. This PR `java.util.UUID` conversion that was missed there.
Fixes: #240
=> Add UUID conversion to class-specific results get

src/main/java/org/duckdb/DuckDBDriver.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
`Driver#getPropertyInfo()` method allows external tools to list configuration options suppored by the DB. This method is pretty obscure and unlikely to be useful with many client tools in practice. But a full list of supported options is required anyway to implement a fix to issue #232, and it makes sense to use `getPropertyInfo` for that as a single method for this functionality.
Testing: new test added.
=> Implement getPropertyInfo method for config list

src/jni/duckdb_java.cpp, src/jni/refs.cpp, src/jni/refs.hpp, src/main/java/org/duckdb/DuckDBDriver.java, src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestClosure.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This change implements `Statement#setQueryTimeout()` method. It is implemented by scheduling a background task and calling `Statement#cancel()` when timeout expires.
Timeouted statement has the same behaviour as it would be if cancelled manually - `SQLException` is thrown and the statement is closed.
Timeout is applied for all `execute*` calls. For `executeBatch()` it is applied separately for every single query in a batch.
Testing: new test added.
Fixes: #212
=> Add support for query timeouts

.github/workflows/Java.yml
This PR brings in the build changes from mainline duckdb/duckdb#17776 fix.
Additionally it enabled test runs on `ubuntu-latest` along with existing EL8 runs.
=> Use devtoolset-12 for Linux glibc builds

src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestBatch.java
This change fixes the problem when connection is left in inconsistent state when `executeBatch` throws constraint (or some other) error with auto-commit enabled.
In #213 `executeBatch` was changed to effectively disable auto-commit for the whole batch. In this case the rollback on error needs to be handled inside `executeBatch` too.
Testing: new tests added that cover constrain violation with `executeBatch`.
Fixes: #259
=> Fix executeBatch in auto-commit mode

.github/workflows/Java.yml
Nightly import of DuckDB engine sources ("vendoring") is performed by creating PRs on `vendoring-<branch>` base branches. After the tests are passed the PR is merged and `vendoring-<branch>` is re-created to be used in subsequent imports.
This change fixes the vendoring branch re-creation to place it not always on the `main` branch, but on the correct branch (either `main` or stable one line `v1.3-ossivalis`).
=> Fix vendoring PRs for stable branches

src/main/java/org/duckdb/DuckDBConnection.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This is a backport of the PR #234 to v1.3-ossivalis stable branch.
Minor change, to allow passing named in-memory connections without double colon prefix. So the following URLs will point to the same in-memory DB:
```
jdbc:duckdb::memory:tag1
jdbc:duckdb:memory:tag1
```
Testing: new test added that check that DB instance cache works correctly with and without second colon in URL.
=> Support memory DBs in URL without leading c. (1.3)

src/main/java/org/duckdb/DuckDBConnection.java, src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/main/java/org/duckdb/DuckDBResultSet.java, src/test/java/org/duckdb/TestClosure.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This is a backport of the PR #242 to `v1.3-ossivalis` stable branch.
When connection is being closed, it closes all statements and all result sets on these statements. All this is done while holding connection lock.
When fetching next chunk, result set needs to take both result set and connection locks. Because of the wrong order of taking these locks, concurrent `close()` call on result set, initiated from `Connection#close()` was causing a deadlock.
This change reorders locks in `ResultSet#fetchChunk()` to fix this.
Testing: new test added that reproduces the deadlock reliably (may need to raise the number of iterations).
Fixes: #241
=> Fix deadlock when fetching next chunk (1.3)

src/main/java/org/duckdb/DuckDBResultSet.java, src/test/java/org/duckdb/TestResults.java
This is a backport of the PR #243 to `v1.3-ossivalis` stable branch.
Result set method `getObject(idx, class)` requires the driver to convert the requested value to the specified class. This PR `java.util.UUID` conversion that was missed there.
Fixes: #240
=> Add UUID conversion to class-specific rs get (1.3)

src/main/java/org/duckdb/DuckDBConnection.java, src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestClosure.java
This is a backport of the PR #245 to `v1.3-ossivalis` stable branch.
`Statement#cancel()` call works on connection level. So currently it is well possible to run query in one statement, and then interrupt this query calling cancel on another statement.
This change adds a check that cancellation can only be performed if the query on current statement is still running. Otherwise `stmt.cancel()` call is a no-op.
Testing: new test added that checks that other statement cannot be cancelled.
=> Do not allow to cancel other running stmts (1.3)

src/jni/duckdb_java.cpp, src/jni/refs.cpp, src/jni/refs.hpp, src/main/java/org/duckdb/DuckDBDriver.java, src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestClosure.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This is a backport of the PR #247 to `v1.3-ossivalis` stable branch.
This change implements `Statement#setQueryTimeout()` method. It is implemented by scheduling a background task and calling `Statement#cancel()` when timeout expires.
Timeouted statement has the same behaviour as it would be if cancelled manually - `SQLException` is thrown and the statement is closed.
Timeout is applied for all `execute*` calls. For `executeBatch()` it is applied separately for every single query in a batch.
Testing: new test added.
Fixes: #212
=> Add support for query timeouts (1.3)

src/main/java/org/duckdb/DuckDBPreparedStatement.java, src/test/java/org/duckdb/TestBatch.java
This is a backport of the PR #261 to `v1.3-ossivalis` stable branch.
This change fixes the problem when connection is left in inconsistent state when `executeBatch` throws constraint (or some other) error with auto-commit enabled.
In #213 `executeBatch` was changed to effectively disable auto-commit for the whole batch. In this case the rollback on error needs to be handled inside `executeBatch` too.
Testing: new tests added that cover constrain violation with `executeBatch`.
Fixes: #259
=> Fix executeBatch in auto-commit mode (1.3)

src/main/java/org/duckdb/DuckDBDriver.java, src/test/java/org/duckdb/TestBatch.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This is a backport of the PR #237 to `v1.3-ossivalis` stable branch.
This change adds support for specifying connection properties as part of the connection string itself. It is intended to be used in cases, when `Properties` map is passed by some tool that does not allow direct access to it, and some of these `Properties` values need to be overridden.
Properties in URL are accepted in `key=value` format, `;` is used as a separator, empty properties are ignored.
URL example: `jdbc:duckdb:;allow_community_extensions=true;;allow_unsigned_extensions = false;`.
Testing: new test added that checks that properties in URL take preference.
=> Support connection properties in URL (1.3)

src/main/java/org/duckdb/DuckDBDriver.java, src/test/java/org/duckdb/TestDuckDBJDBC.java
This is a backport of the PR #244 to `v1.3-ossivalis` stable branch.
`Driver#getPropertyInfo()` method allows external tools to list configuration options suppored by the DB. This method is pretty obscure and unlikely to be useful with many client tools in practice. But a full list of supported options is required anyway to implement a fix to issue #232, and it makes sense to use `getPropertyInfo` for that as a single method for this functionality.
Testing: new test added.
=> Implement getPropertyInfo method for config (1.3)

src/main/java/org/duckdb/DuckDBConnection.java, src/main/java/org/duckdb/DuckDBDriver.java, src/main/java/org/duckdb/JdbcUtils.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/TestSessionInit.java, src/test/java/org/duckdb/test/TempDirectory.java
This is a backport of the PR #252 to `v1.3-ossivalis` stable branch.
This change adds support for `session_init_sql_file` connection option, that allows to speficy the path to an SQL file in local file system, that will be read by the driver and executed in a newly created connection before passing it to user.
By default the file is initalized only once per database, on the first connection established to this DB.
For `:memory:` connection-private DBs it effectively executed once per connection.
In addition to the DB init, it supports executing a part of the SQL file for every connection. It looks for the specific marker:
```
/* DUCKDB_CONNECTION_INIT_BELOW_MARKER */
```
in the SQL file. If this marker is present - everything before the marker is executed on DB init, and everything after …
=> Support running an SQL file on init (1.3)

src/duckdb/src/common/virtual_file_system.cpp, src/duckdb/src/function/table/version/pragma_version.cpp, src/duckdb/src/include/duckdb/main/extension_entries.hpp
Changes:
- [duckdb/duckdb#2063dda3e6](https://github.com/duckdb/duckdb/commit/2063dda3e6) imported at 2025-06-16 14:03:37
=> Update vendored DuckDB sources to 2063dda3e6

src/test/java/org/duckdb/TestDuckDBJDBC.java
This change makes the query progress test to be compatible with the CTE changes done in duckdb/duckdb#17459, see duckdb/duckdb#18017 for details.
=> Fix query progress test

src/main/java/org/duckdb/JdbcUtils.java
With the changes introduced in #276 the `jdbc:duckdb:ducklake:...` URLs have the special handling: `jdbc_pin_db` and `jdbc_stream_results` options are applied to them automatically. This behaviour was supposed to be overridable with URL or `Properties` but by mistake incorrect method was used for override check. And as DuckLake is still not available in the `main` branch, there is no test coverage for this and the problem got into `1.3.1.0` update.
Fixes: #283
=> DuckLake options override fix

src/main/java/org/duckdb/JdbcUtils.java
This is a backport of the PR #287 to `v1.3-ossivalis` stable branch.
With the changes introduced in #276 the `jdbc:duckdb:ducklake:...` URLs have the special handling: `jdbc_pin_db` and `jdbc_stream_results` options are applied to them automatically. This behaviour was supposed to be overridable with URL or `Properties` but by mistake incorrect method was used for override check. And as DuckLake is still not available in the `main` branch, there is no test coverage for this and the problem got into `1.3.1.0` update.
Fixes: #283
=> DuckLake options override fix (1.3)

.github/workflows/Java.yml, scripts/jdbc_maven_deploy.py
This change switches the Maven Central publishing process from using OSSRH (that is
[discontinued](https://central.sonatype.org/pages/ossrh-eol/)), to using Portal Publisher API calling it with cURL utility.
Testing: these changes were used to successfully publish 1.3.2.0 update
=> Use Portal API to publish to Maven Central

src/duckdb/src/function/table/version/pragma_version.cpp
Changes:
- [duckdb/duckdb#2efc9ec537](https://github.com/duckdb/duckdb/commit/2efc9ec537) imported at 2025-07-30 05:41:17
=> Update vendored DuckDB sources to 2efc9ec537

src/main/java/org/duckdb/DuckDBAppender.java, src/main/java/org/duckdb/DuckDBBindings.java, src/test/java/org/duckdb/TestAppender.java
Previously, attempting to append a UUID would result in an `unsupported C API type: 27` error which is documented in https://github.com/duckdb/duckdb-java/issues/313. This change enables the `DuckDBAppender` to handle `java.util.UUID` objects directly.
=> Add UUID support to `DuckDBAppender` (fixes #313)

src/duckdb/src/common/error_data.cpp, src/duckdb/src/function/table/version/pragma_version.cpp, src/duckdb/src/include/duckdb/common/error_data.hpp, src/duckdb/src/include/duckdb/storage/compression/dict_fsst/compression.hpp, src/duckdb/src/storage/compression/dict_fsst/compression.cpp, src/duckdb/src/transaction/duck_transaction_manager.cpp, src/duckdb/src/transaction/meta_transaction.cpp
Changes:
- [duckdb/duckdb#0e258ecaaf](https://github.com/duckdb/duckdb/commit/0e258ecaaf) imported at 2025-08-02 05:35:25
- [duckdb/duckdb#67cbce34e1](https://github.com/duckdb/duckdb/commit/67cbce34e1) imported at 2025-08-05 06:15:38
=> Update vendored DuckDB sources to 67cbce34e1

src/duckdb/src/execution/join_hashtable.cpp, src/duckdb/src/include/duckdb/execution/ht_entry.hpp, src/duckdb/src/include/duckdb/execution/join_hashtable.hpp
This PR contains a cherry-pick of the duckdb/duckdb#18752 engine PR applied on top of the `v1.3.2.0` release. `v1.3.2` branch is created for it so the new release built from this branch will be compatible with existing `v1.3.2` extensions.
Testing: test case included with the original PR is run manually on patched JDBC.
=> Backport #18374 engine fix to v1.3.2 branch

src/duckdb/src/function/table/version/pragma_version.cpp, src/duckdb/src/include/duckdb/storage/table/row_group.hpp, src/duckdb/src/include/duckdb/storage/table/row_id_column_data.hpp, src/duckdb/src/storage/table/row_group.cpp, src/duckdb/src/storage/table/row_id_column_data.cpp, src/duckdb/ub_src_storage_table.cpp
Changes:
- [duckdb/duckdb#036b9bc3f9](https://github.com/duckdb/duckdb/commit/036b9bc3f9) imported at 2025-08-30 04:17:59
=> Update vendored DuckDB sources to 036b9bc3f9

.github/workflows/Java.yml
This change revert the usage of `gcc-toolset-12` for `x86_64` and `aarch64` Linux builds. See duckdb/duckdb#17963 for details.
=> Revert GCC 12 downgrade for Linux builds

src/duckdb/src/common/sorting/hashed_sort.cpp, src/duckdb/src/execution/operator/schema/physical_attach.cpp, src/duckdb/src/function/table/version/pragma_version.cpp, src/duckdb/src/include/duckdb/main/attached_database.hpp, src/duckdb/src/include/duckdb/main/database_file_path_manager.hpp, src/duckdb/src/include/duckdb/main/database_manager.hpp, src/duckdb/src/main/attached_database.cpp, src/duckdb/src/main/database.cpp, src/duckdb/src/main/database_file_path_manager.cpp, src/duckdb/src/main/database_manager.cpp
Changes:
- [duckdb/duckdb#82446e8a32](https://github.com/duckdb/duckdb/commit/82446e8a32) imported at 2025-09-14 04:08:25
=> Update vendored DuckDB sources to 82446e8a32

src/duckdb/src/catalog/catalog.cpp, src/duckdb/src/common/sorting/hashed_sort.cpp, src/duckdb/src/execution/operator/schema/physical_attach.cpp, src/duckdb/src/function/table/table_scan.cpp, src/duckdb/src/function/table/version/pragma_version.cpp, src/duckdb/src/include/duckdb/catalog/catalog.hpp, src/duckdb/src/include/duckdb/main/attached_database.hpp, src/duckdb/src/include/duckdb/main/database_file_path_manager.hpp, src/duckdb/src/include/duckdb/main/database_manager.hpp, src/duckdb/src/include/duckdb/main/extension_entries.hpp, src/duckdb/src/include/duckdb/storage/checkpoint/table_data_writer.hpp, src/duckdb/src/include/duckdb/storage/metadata/metadata_manager.hpp, src/duckdb/src/include/duckdb/storage/table/in_memory_checkpoint.hpp, src/duckdb/src/include/duckdb/storage/table/row_group_collection.hpp, src/duckdb/src/main/attached_database.cpp, src/duckdb/src/main/database.cpp, src/duckdb/src/main/database_file_path_manager.cpp, src/duckdb/src/main/database_manager.cpp, src/duckdb/src/storage/checkpoint/table_data_writer.cpp, src/duckdb/src/storage/data_table.cpp, src/duckdb/src/storage/metadata/metadata_manager.cpp, src/duckdb/src/storage/table/in_memory_checkpoint.cpp, src/duckdb/src/storage/table/row_group.cpp, src/duckdb/src/storage/table/row_group_collection.cpp, src/duckdb/third_party/httplib/httplib.hpp
Changes:
- [duckdb/duckdb#19dd651b26](https://github.com/duckdb/duckdb/commit/19dd651b26) imported at 2025-09-15 04:34:18
=> Update vendored DuckDB sources to 19dd651b26

src/main/java/org/duckdb/DuckDBResultSetMetaData.java, src/test/java/org/duckdb/TestResults.java
This is a backport of the PR #367 to `v1.4-andium` stable branch.
This PR makes `ResultSetMetaData#getPrecision()` to return non-zero values for integral numbers, floating point, date/time and string columns.
Unlike the `DECIMAL` type, where actual column precision is returned, for other types this call is expected to give a hint to a client software how much space the textual representation of the field is going to take. Previously returned 0 value appeared to cause problems in some of such clients.
Values returned are consistent with ones returned by Postgres.
Testing: new test added for all types.
Fixes: #340
=> Return precision values for non-dec columns (1.4)

src/main/java/org/duckdb/DuckDBTimestamp.java, src/test/java/org/duckdb/TestDuckDBJDBC.java, src/test/java/org/duckdb/TestTimestamp.java
This is a backport of the PR #377 to `v1.4-andium` stable branch.
This PR fixes the problem with converting `TIMESTAMP` values into `LocalDateTime` where, when micros/nanos part was present, the calculation may have been shifted by 1 second.
Fixes: #336
=> Fix timestamp before epoch with micros/nanos (1.4)

.github/workflows/Java.yml, CMakeLists.txt, CMakeLists.txt.in
This PR is a follow-up to #164 change, it fixes the exported symbols for MacOS and adds listing of symbols on CI runs.
=> Fix exported symbols on Mac

.github/workflows/Java.yml, CMakeLists.txt, CMakeLists.txt.in
This is a backport of the PR #386 to `v1.4-andium` stable branch.
This PR is a follow-up to #164 change, it fixes the exported symbols for MacOS and adds listing of symbols on CI runs.
=> Fix exported symbols on Mac (1.4)

src/main/java/org/duckdb/DuckDBAppender.java, src/test/java/org/duckdb/TestAppender.java
This is a backport of the PR #396 to `v1.4-andium` stable branch.
This PR adds support to nested `STRUCT` and `UNION` columns in `Appender`. There are no nesting limit enforced on Java side.
Testing: existing test is extended to cover nested `STRUCT`s.
=> Appender: support nested STRUCTs (1.4)

src/duckdb/extension/parquet/column_writer.cpp, src/duckdb/extension/parquet/geo_parquet.cpp, src/duckdb/extension/parquet/include/column_writer.hpp, src/duckdb/extension/parquet/include/geo_parquet.hpp, src/duckdb/extension/parquet/include/parquet_writer.hpp, src/duckdb/extension/parquet/parquet_extension.cpp, src/duckdb/extension/parquet/parquet_writer.cpp, src/duckdb/extension/parquet/writer/primitive_column_writer.cpp, src/duckdb/src/function/table/version/pragma_version.cpp, src/duckdb/src/include/duckdb/main/relation.hpp, src/duckdb/src/include/duckdb/main/relation/create_table_relation.hpp, src/duckdb/src/include/duckdb/main/relation/create_view_relation.hpp, src/duckdb/src/include/duckdb/main/relation/delete_relation.hpp, src/duckdb/src/include/duckdb/main/relation/explain_relation.hpp, src/duckdb/src/include/duckdb/main/relation/insert_relation.hpp, src/duckdb/src/include/duckdb/main/relation/query_relation.hpp, src/duckdb/src/include/duckdb/main/relation/update_relation.hpp, src/duckdb/src/include/duckdb/main/relation/write_csv_relation.hpp, src/duckdb/src/include/duckdb/main/relation/write_parquet_relation.hpp, src/duckdb/src/main/relation.cpp, src/duckdb/src/main/relation/create_table_relation.cpp, src/duckdb/src/main/relation/create_view_relation.cpp, src/duckdb/src/main/relation/delete_relation.cpp, src/duckdb/src/main/relation/explain_relation.cpp, src/duckdb/src/main/relation/insert_relation.cpp, src/duckdb/src/main/relation/query_relation.cpp, src/duckdb/src/main/relation/update_relation.cpp, src/duckdb/src/main/relation/write_csv_relation.cpp, src/duckdb/src/main/relation/write_parquet_relation.cpp, src/duckdb/src/parser/statement/relation_statement.cpp
Changes:
- [duckdb/duckdb#b390a7c376](https://github.com/duckdb/duckdb/commit/b390a7c376) imported at 2025-10-04 03:35:16
=> Update vendored DuckDB sources to b390a7c376

src/duckdb/src/function/table/version/pragma_version.cpp
Changes:
- [duckdb/duckdb#cdf9e7c1e8](https://github.com/duckdb/duckdb/commit/cdf9e7c1e8) imported at 2025-10-07 05:02:51
=> Update vendored DuckDB sources to cdf9e7c1e8
